### PR TITLE
Addition of API for custom shapes and exocomets

### PR DESCRIPTION
**Pull request by martindevora**
Thank you for your contribution to TLS. 
Before submitting this PR, please make sure:

- [OK ] Your code builds clean without any errors or warnings
- [OK ] [Existing test cases](https://github.com/hippke/tls/tree/master/transitleastsquares/tests) work correctly
- [OK ] New test cases have been added to cover the additional and/or changed functionality

### CODE REVIEW

**Comment by martindevora** [comment]
It seems that there is a CI check that is failing. However, I'm looking at the failed builds and it seems that they are being executed by cloning the official repository. Thus, the new python subpackage cannot be found.

**Comment by hippke** [comment]
Hi @martindevora, thank you so much for the PR! I am delighted to see this cool new feature become part of the next TLS release.

I will need a few days to inspect the changes. Do I understand correctly that the interface to the new transit shapes is build in such a way, so that the old interface still works? In other words: There are many people out there using the old (default) transit shapes - will they still work without changes?

I also saw your iPython Notebooks and think they are a very good starting point. I have a few suggestions for improvements and will get back to you with more details in a few days.

**Comment by martindevora** [comment]
> Hi @martindevora, thank you so much for the PR! I am delighted to see this cool new feature become part of the next TLS release.

> I will need a few days to inspect the changes. Do I understand correctly that the interface to the new transit shapes is build in such a way, so that the old interface still works? In other words: There are many people out there using the old (default) transit shapes - will they still work without changes?
> 
Totally! If not, it'd be a bug.

> I also saw your iPython Notebooks and think they are a very good starting point. I have a few suggestions for improvements and will get back to you with more details in a few days.

Great. I'm open to any comments : )

PS1: We could leave the comets implementation out of this PR if you think that we should review it separately.
PS2: The comets new template could probably be fed with two or three parameters (ingress and egress params and maximum depth Time) which could be introduced from the power function. This is not already done, but it should not take much additional effort from my side. What do you think about it?

**Comment by martindevora** [comment]
I've been thinking about the solution and I think that it can be improved at the compilation of the results. We could define a base TransitResult class that could be implemented by each TransitTemplateGenerator class. That way we'd be open to any physical characterization other than planetary transits. What do you think?

**Comment by hippke** [comment]
Sorry for the delay! I appreciate your contribution enormously. I just don't have enough time at the moment to check everything in detail. Right now, schools are closed, so that I'm tasked with double duty of day job and home schooling of my two kids. It's very tiring.

Regarding the base TransitResult class: I think it would be really cool if the user can define arbitrary functions to be searched for. My only caveat is to keep it as simple as possible for the user. The majority of our users are Python beginners. I get many questions via e-mail where people struggle with simple things. So yeah, if we can make it simple, let's do it!

**Comment by martindevora** [comment]
> Sorry for the delay! I appreciate your contribution enormously. I just don't have enough time at the moment to check everything in detail. Right now, schools are closed, so that I'm tasked with double duty of day job and home schooling of my two kids. It's very tiring.

I'm under the same circumstances so I can fully understand you. No worries!

> Regarding the base TransitResult class: I think it would be really cool if the user can define arbitrary functions to be searched for. My only caveat is to keep it as simple as possible for the user. The majority of our users are Python beginners. I get many questions via e-mail where people struggle with simple things. So yeah, if we can make it simple, let's do it!

I'm trying to make the changes in such a way that beginner users or code-agnostic people can still work transparently as they were doing before without knowing or touching any code. However, in order to inject a new template into TLS I think that some little bits of coding skills are needed. I mean, one at least would need to know how to create a new template model programmatically. Keeping that in mind, I'll try to keep things as simpler as possible for the TLS main user profiles and in the worst case you can reject the changes or make a constructive review to improve the solution if you find it too complex for them : )

**Pull request closed without merging**
